"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),{TravelAgent}=require("../tourism/agent-runner.cjs"),{scenario}=require("../tourism/demo-data.js"),{startServer}=require("../tourism/agent-server.cjs");
const mockConfig=()=>({providerId:"mock",model:"mock-model",host:"test.invalid",key:"",url:"https://test.invalid/chat/completions"});
function transport(calls=[]){return async(config,body)=>{calls.push(body);const name=body.tools?.[0]?.function.name;if(name==="prepare_travel_request"){const r=scenario().request;return{message:{tool_calls:[{id:"call",function:{name,arguments:JSON.stringify({request:Object.fromEntries(["destination","days","adults","children","seniors","budget","maxWalkingMinutes","weather","avoidOutdoorInRain","interests","dietary","accessibility"].map(k=>[k,r[k]])),questions:[],evidence:[{target:"request",excerpt:"游客原文"}]})}}]},usage:{total_tokens:20}};}if(name==="submit_grounded_answer")return{message:{tool_calls:[{id:"answer",function:{name,arguments:JSON.stringify({answer:"依据事实卡回答",citations:["SIM-F07"],unknowns:[],conflicts:[],suggestedQuestions:[]})}}]},usage:{total_tokens:10}};return{message:{content:"模拟模型生成的文旅草稿。"},usage:{total_tokens:10}};};}
async function evaluated(agent,task=scenario(),selectedPlanId="A"){const{sessionId}=await agent.run({action:"new"}),out=await agent.run({action:"evaluate",sessionId,task,selectedPlanId});return{sessionId,task,out};}

test("S04 无模型配置仍可本地评估并生成诊断报告",async()=>{const agent=new TravelAgent({config:()=>{throw new Error("无模型");}}),{sessionId}=await agent.run({action:"new"}),out=await agent.run({action:"evaluate",sessionId,task:scenario()});assert.equal(out.result.cheapest,"A");assert.match(out.report,/2130/);assert.equal(agent.status().available,false);agent.close();});
test("S02 approved=true 不能绕过服务端确认生成",async()=>{const agent=new TravelAgent({config:mockConfig,transport:transport()}),{sessionId,task,out}=await evaluated(agent);await assert.rejects(agent.run({action:"generate",sessionId,kind:"service",task,taskHash:out.result.taskHash,selectedPlanId:"A",approved:true}),/确认/);agent.close();});
test("确认绑定服务端评估、taskHash 与 selectedPlanId",async()=>{const agent=new TravelAgent({config:mockConfig,transport:transport()}),{sessionId,task,out}=await evaluated(agent),confirmed=await agent.run({action:"confirm",sessionId,task,taskHash:out.result.taskHash,selectedPlanId:"A",acknowledged:true});assert.equal(confirmed.confirmation.taskHash,out.result.taskHash);assert.equal(confirmed.confirmation.selectedPlanId,"A");assert.ok(confirmed.confirmation.confirmationId);agent.close();});
test("S01 确认后改变预算或方案会拒绝旧确认",async()=>{const agent=new TravelAgent({config:mockConfig,transport:transport()}),{sessionId,task,out}=await evaluated(agent),c=(await agent.run({action:"confirm",sessionId,task,taskHash:out.result.taskHash,selectedPlanId:"A",acknowledged:true})).confirmation,changed=structuredClone(task);changed.request.budget++;await assert.rejects(agent.run({action:"generate",sessionId,kind:"service",task:changed,taskHash:c.taskHash,selectedPlanId:"A",confirmationId:c.confirmationId}),/变化|确认/);await assert.rejects(agent.run({action:"generate",sessionId,kind:"service",task,taskHash:c.taskHash,selectedPlanId:"B",confirmationId:c.confirmationId}),/变化|确认/);agent.close();});
test("S05 pending 方案可诊断但不能确认和生成",async()=>{const agent=new TravelAgent({config:mockConfig,transport:transport()}),{sessionId,task,out}=await evaluated(agent,scenario(),"C");assert.equal(out.result.rows.find(x=>x.id==="C").status,"pending");await assert.rejects(agent.run({action:"confirm",sessionId,task,taskHash:out.result.taskHash,selectedPlanId:"C",acknowledged:true}),/只有通过/);agent.close();});
test("三类固定交付都绑定同一确认且无需模型",async()=>{const agent=new TravelAgent({config:()=>{throw new Error("不得调用");}}),{sessionId,task,out}=await evaluated(agent),c=(await agent.run({action:"confirm",sessionId,task,taskHash:out.result.taskHash,selectedPlanId:"A",acknowledged:true})).confirmation;for(const kind of ["service","marketing","product"]){const generated=await agent.run({action:"generate",sessionId,kind,task,taskHash:c.taskHash,selectedPlanId:"A",confirmationId:c.confirmationId,useModel:false});assert.equal(generated.deliverable.confirmationId,c.confirmationId);assert.equal(generated.deliverable.kind,kind);assert.match(generated.content,/模拟实训/);}agent.close();});
test("D02 营销模型传输只包含允许投影",async()=>{const calls=[],agent=new TravelAgent({config:mockConfig,transport:transport(calls)}),task=scenario();task.request.dietary="SECRET-DIET";task.request.accessibility="SECRET-ACCESS";const{sessionId,out}=await evaluated(agent,task),c=(await agent.run({action:"confirm",sessionId,task,taskHash:out.result.taskHash,selectedPlanId:"A",acknowledged:true})).confirmation;await agent.run({action:"generate",sessionId,kind:"marketing",task,taskHash:c.taskHash,selectedPlanId:"A",confirmationId:c.confirmationId,useModel:true});const body=JSON.stringify(calls.at(-1));assert.ok(!body.includes("SECRET-DIET"));assert.ok(!body.includes("SECRET-ACCESS"));assert.ok(!body.includes("dietaryRequirements"));agent.close();});
test("K03 咨询模型非法 factId 引用不会成为有效引用",async()=>{const bad=async()=>({message:{tool_calls:[{id:"x",function:{name:"submit_grounded_answer",arguments:JSON.stringify({answer:"越界",citations:["NOT-PROVIDED"],unknowns:[],conflicts:[],suggestedQuestions:[]})}}]}}),agent=new TravelAgent({config:mockConfig,transport:bad}),{sessionId}=await agent.run({action:"new"}),out=await agent.run({action:"consult",sessionId,task:scenario(),question:"水乡家宴花生",resourceId:"localmeal",useModel:true});assert.equal(out.answer.valid,false);assert.deepEqual(out.answer.citations,[]);assert.ok(out.answer.invalidCitations.includes("NOT-PROVIDED"));agent.close();});
test("需求模型不能修改资源、事实、交通与候选",async()=>{const agent=new TravelAgent({config:mockConfig,transport:transport()}),base=scenario(),{sessionId}=await agent.run({action:"new"}),draft=await agent.run({action:"extract",sessionId,text:"游客原文",demo:true,basePayload:base});for(const key of ["resources","facts","transfers","plans"])assert.deepEqual(draft.payload[key],base[key]);agent.close();});
test("工具白名单拒绝命令执行类调用",async()=>{const agent=new TravelAgent({config:mockConfig,transport:async()=>({message:{tool_calls:[{function:{name:"exec_shell",arguments:'{"command":"bad"}'}}]}})}),{sessionId}=await agent.run({action:"new"});await assert.rejects(agent.run({action:"extract",sessionId,text:"游客原文",demo:true,basePayload:scenario()}),/限定工具/);agent.close();});
test("S03 invalidate 取消在途模型请求且会话旧结果不能落地",async()=>{const agent=new TravelAgent({config:mockConfig,transport:async(c,b,signal)=>new Promise((resolve,reject)=>signal.addEventListener("abort",()=>reject(new Error("aborted"))))}),{sessionId}=await agent.run({action:"new"}),running=agent.run({action:"extract",sessionId,text:"游客原文",demo:true,basePayload:scenario()}),rejected=assert.rejects(running,/aborted/);await new Promise(r=>setImmediate(r));agent.sessions.get(sessionId).controller.abort();await rejected;await agent.run({action:"invalidate",sessionId,reason:"导入新任务"});assert.equal(agent.sessions.get(sessionId).confirmation,null);agent.close();});
test("reset 与 close 释放会话并禁止后续使用",async()=>{const agent=new TravelAgent({config:mockConfig,transport:transport()}),{sessionId}=await agent.run({action:"new"});await agent.run({action:"reset",sessionId});await assert.rejects(agent.run({action:"evaluate",sessionId,task:scenario()}),/过期/);agent.close();await assert.rejects(agent.run({action:"status"}),/关闭/);});
test("本机服务拒绝外站和无令牌调用并释放端口",async()=>{const app=await startServer({agent:new TravelAgent({config:mockConfig,transport:transport()})}),origin=app.origin;try{const html=await(await fetch(origin)).text();assert.match(html,/TravelAgentRequest/);assert.ok(!html.includes("mock-model"));assert.equal((await fetch(origin+"/api/agent",{method:"POST",body:'{"action":"status"}'})).status,403);assert.equal((await fetch(origin+"/api/agent",{method:"POST",headers:{Origin:"https://untrusted.invalid"},body:"{}"})).status,403);}finally{await app.close();}await assert.rejects(fetch(origin));});
