"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),{spawnSync}=require("node:child_process"),root=path.resolve(__dirname,"..");
test("V5桌面前端保持完整功能并加载文旅入口",()=>{const bundle=fs.readFileSync(path.join(root,"dist/index-v4.js"),"utf8");for(const marker of ['appName:"旅策协同"','authMode:"standalone"','heartbeatUrl:""','skillHubEndpoint:""','doctor:!1','旅策协同 模型设置','旅策协同 本机检查','travel-diagnostics-button','travel-open-local-check','"sidebar.doctor":"本机检查"','"startup.runDiagnostics":"本机检查"','TravelSkillMarketPolicy','filterSkillMarketCategories','market-skill-card-','tv-launch','服务端确认与 Skill 协同交付','settings.dreaming.title','doctor.memory.dreamDiary','setDreamingEnabled','visibleViews:["chat","channels","agents","cron","skills","my-files","logs"]'])assert.match(bundle,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(bundle,/authMode:"oauth2"|me\.openDoctorWindow\(\)/);assert.equal(require("../tools/brand-audit.cjs").inspect("dist/index-v4.js",Buffer.from(bundle)),null);});
test("模型设置覆盖所需服务并限制远程HTTP",()=>{const source=fs.readFileSync(path.join(root,"internal-model-settings.js"),"utf8");assert.doesNotThrow(()=>new Function(source));for(const marker of ["api.deepseek.com/v1","dashscope.aliyuncs.com/compatible-mode/v1","api.moonshot.cn/v1","api.openai.com/v1","127.0.0.1:11434/v1","127.0.0.1:1234/v1","旅策协同 模型设置","远程模型服务必须使用 HTTPS"])assert.match(source,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(source,/localStorage|sessionStorage/);});
function pngs(bytes){const sig=Buffer.from("89504e470d0a1a0a","hex"),out=[];for(let cursor=0;(cursor=bytes.indexOf(sig,cursor))!==-1;cursor+=8){let pos=cursor+8,w=0,h=0;while(pos+12<=bytes.length){const len=bytes.readUInt32BE(pos),type=bytes.toString("ascii",pos+4,pos+8);if(len>128*1024*1024||pos+12+len>bytes.length)break;if(type==="IHDR"){w=bytes.readUInt32BE(pos+8);h=bytes.readUInt32BE(pos+12);}pos+=12+len;if(type==="IEND"){out.push({w,h,hash:crypto.createHash("sha256").update(bytes.subarray(cursor,pos)).digest("hex")});break;}}}return out;}
function count(bytes,needle){let n=0,c=0;while((c=bytes.indexOf(needle,c))!==-1){n++;c+=needle.length;}return n;}
test("桌面运行文件、标题、入口和图标使用旅策协同品牌",()=>{const launcher=fs.readFileSync(path.join(root,"launcher.cjs"),"utf8"),bundle=fs.readFileSync(path.join(root,"dist","index-v4.js"),"utf8"),helper=fs.readFileSync(path.join(root,"native-brand.ps1"),"utf8"),runtime=fs.readFileSync(path.join(root,"runtime","旅策协同.exe")),icons=pngs(runtime),oldProduct=Buffer.from([99,99,108,97,119]),oldVendor=Buffer.from([99,104,97,110,106,101,116]);assert.match(launcher,/index-v4\.js/);assert.match(launcher,/travel\.ico/);assert.match(launcher,/旅策协同\.exe/);assert.match(launcher,/modelConfigPaths/);assert.match(bundle,/homeDir:"\.tr-ai-assist"/);assert.match(bundle,/configFileName:"tr-ai-assist\.json"/);assert.match(helper,/0x65C5.*0x7B56.*0x534F.*0x540C/);assert.match(fs.readFileSync(path.join(root,"旅策协同桌面版.vbs"),"utf8"),/launcher\.cjs/);assert.ok(count(runtime,Buffer.from("TR.AI"))>=9);assert.ok(count(runtime,Buffer.from("tr-ai"))>=26);assert.equal(count(runtime,oldProduct),0);assert.equal(count(runtime,oldVendor),0);assert.ok(icons.some(x=>x.w===44&&x.h===44));assert.ok(icons.some(x=>x.w===1024&&x.h===1024));const parsed=spawnSync("powershell.exe",["-NoProfile","-Command",`$null=[System.Management.Automation.Language.Parser]::ParseFile('${path.join(root,"native-brand.ps1").replaceAll("'","''")}',[ref]$null,[ref]$null)`],{encoding:"utf8",windowsHide:true});assert.equal(parsed.status,0,parsed.stderr);});
test("运行时只暴露三个文旅Skills且结构有效",()=>{const skills=fs.readdirSync(path.join(root,"runtime","skills"),{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name).sort();assert.deepEqual(skills,["travel-content-lab","travel-demand-planner","travel-service-coordinator"]);const yaml=require("../runtime/openclaw/node_modules/yaml");for(const name of skills){const source=fs.readFileSync(path.join(root,"runtime","skills",name,"SKILL.md"),"utf8"),front=source.match(/^---\r?\n([\s\S]*?)\r?\n---/);assert.ok(front,name);const meta=yaml.parse(front[1]);assert.equal(meta.name,name);assert.ok(meta.description.length>30);assert.doesNotMatch(source,/TODO|\[INSERT/);}});
test("发布入口和运行时只保留当前课题",()=>{const {releaseFiles}=require("../tools/release-policy.cjs");const files=releaseFiles();assert.equal(files.some(x=>x.startsWith(".development/")||x.startsWith("build-input/")),false);const entrypoints=fs.readdirSync(root).filter(x=>x.endsWith(".vbs")).sort();assert.deepEqual(entrypoints,["旅策协同文旅Agent.vbs","旅策协同桌面版.vbs"].sort());assert.equal(fs.existsSync(path.join(root,"competition")),false);});
