(function(root){
  "use strict";
  const $=id=>document.getElementById(`ta-${id}`),el=(tag,attrs={},children=[])=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==="text")n.textContent=v;else if(k==="class")n.className=v;else if(k.startsWith("on"))n.addEventListener(k.slice(2),v);else if(v!==undefined&&v!==null)n.setAttribute(k,v);}for(const c of children)n.append(c);return n;},btn=(text,onclick,id)=>el("button",{type:"button",text,onclick,id:`ta-${id}`});
  let sessionId=null,confirmation=null,busy=false,latest=null,sequence=0;
  const request=payload=>root.TravelAgentRequest(payload),status=(message,error=false)=>{if($("status")){$("status").textContent=message;$("status").dataset.kind=error?"error":"info";}},download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=el("a",{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);};
  async function ensure(){if(!root.TravelAgentRequest)throw new Error("离线模式没有本机 Agent 服务。");if(!sessionId)sessionId=(await request({action:"new"})).sessionId;}
  function renderTrace(trace=[]){$("trace").replaceChildren(...trace.slice(-12).map(x=>el("li",{text:`${x.time||""} · ${x.type||"步骤"}`})));}
  function options(){return{channel:$("channel").value,audience:$("audience").value,length:$("length").value,theme:$("theme").value,approvedPublicText:$("approved").value};}
  async function evaluate(){if(busy)return;const own=++sequence;busy=true;try{await ensure();const task=root.TravelWorkbench.read(),out=await request({action:"evaluate",sessionId,task,selectedPlanId:root.TravelWorkbench.selectedPlanId()});if(own!==sequence)return;latest=out;root.TravelWorkbench.result(out.result);$("plan").value=out.selectedPlanId||"";confirmation=null;renderTrace(out.trace);status(`服务端已按任务哈希 ${out.result.taskHash} 完成本地评估。`);}catch(error){if(own===sequence)status(error.message,true);}finally{if(own===sequence)busy=false;}}
  async function confirmCurrent(){if(busy)return;const own=++sequence;busy=true;try{if(!latest)throw new Error("请先同步服务端评估。");const task=root.TravelWorkbench.read(),selectedPlanId=root.TravelWorkbench.selectedPlanId()||$("plan").value;if(!selectedPlanId)throw new Error("请选择方案。");const out=await request({action:"confirm",sessionId,task,taskHash:latest.result.taskHash,selectedPlanId,acknowledged:$("ack").checked});if(own!==sequence)return;confirmation=out.confirmation;renderTrace(out.trace);status(`当前方案已建立服务端确认：${confirmation.confirmationId}`);}catch(error){if(own===sequence)status(error.message,true);}finally{if(own===sequence)busy=false;}}
  function preview(){try{if(!latest)throw new Error("请先完成服务端评估。");const task=root.TravelWorkbench.read(),selected=root.TravelWorkbench.selectedPlanId()||$("plan").value;if(!selected)throw new Error("请选择方案。");const data=root.TravelDeliverables.publicProjection(task,latest.result,selected,options());$("preview").textContent=JSON.stringify(data,null,2);$("preview-box").open=true;status("已显示将用于营销/创意生成的公开字段投影；不含游客原文和个人自由文本。");}catch(error){status(error.message,true);}}
  async function generate(kind){if(busy)return;const own=++sequence;busy=true;try{if(!confirmation)throw new Error("请先建立当前方案确认。");const task=root.TravelWorkbench.read(),out=await request({action:"generate",sessionId,kind,task,taskHash:confirmation.taskHash,selectedPlanId:confirmation.selectedPlanId,confirmationId:confirmation.confirmationId,useModel:$("model").checked,options:options()});if(own!==sequence)return;$("output").value=out.deliverable.content;latest={...latest,deliverable:out.deliverable};renderTrace(out.trace);status(`${({service:"服务接待",marketing:"营销",product:"产品创意"})[kind]}草稿已生成；可继续人工编辑后导出。`);}catch(error){if(own===sequence)status(error.message,true);}finally{if(own===sequence)busy=false;}}
  async function cancel(){sequence++;busy=false;const old=sessionId;sessionId=null;confirmation=null;latest=null;if(old)try{await request({action:"reset",sessionId:old});}catch{}status("当前 Agent 请求已取消；迟到响应不会写入工作台。");}
  function exportCurrent(format){if(!latest?.deliverable)return status("尚无可导出的交付物。",true);const content=$("output").value,item={...latest.deliverable,content,edited:content!==latest.deliverable.content};if(format==="json")download(`旅策协同-${item.kind}.json`,JSON.stringify(item,null,2),"application/json;charset=utf-8");else download(`旅策协同-${item.kind}.md`,root.TravelDeliverables.toMarkdown(item),"text/markdown;charset=utf-8");}
  async function invalidate(){sequence++;busy=false;confirmation=null;latest=null;if($("ack"))$("ack").checked=false;if($("output"))$("output").value="";if(sessionId)try{await request({action:"invalidate",sessionId,reason:"工作台任务或选定方案已变化"});}catch{}status(root.TravelAgentRequest?"任务已变化；服务端确认和旧交付资格已失效。":"离线模式：任务已变化，本地评估仍可使用；服务端确认不可用。");}
  function install(){if($("panel")||!root.TravelWorkbench)return;const slot=document.getElementById("tv-service-slot")?.parentElement||document.getElementById("tv-area-3"),panel=el("div",{id:"ta-panel",class:"ta-panel"},[
    el("h3",{text:"服务端确认与 Skill 协同交付"}),el("p",{class:"tv-note",text:"评估、预览和固定模板不调用模型。只有勾选“使用已配置模型”并点击生成时才产生模型用量。"}),
    el("div",{class:"tv-controls"},[btn("同步服务端评估",evaluate,"evaluate"),el("input",{id:"ta-plan",placeholder:"方案 ID",readonly:""}),el("label",{},[el("input",{id:"ta-ack",type:"checkbox"})," 我已核对当前任务与选定方案"]),btn("建立当前确认",confirmCurrent,"confirm"),btn("取消当前请求",cancel,"cancel")]),
    el("div",{class:"tv-form"},[el("label",{class:"tv-field"},["营销渠道",el("select",{id:"ta-channel"},[["公众号","公众号"],["短视频","短视频"],["社交平台","社交平台"],["线下物料","线下物料"]].map(([v,n])=>el("option",{value:v,text:n})))]),el("label",{class:"tv-field"},["目标受众",el("input",{id:"ta-audience",value:"亲子文化体验兴趣人群"})]),el("label",{class:"tv-field"},["内容主题",el("input",{id:"ta-theme",value:"在地文化深度体验"})]),el("label",{class:"tv-field"},["内容篇幅",el("select",{id:"ta-length"},["精简","中等","详细"].map(v=>el("option",{value:v,text:v})))]),el("label",{class:"tv-field"},["人工批准的公开补充",el("input",{id:"ta-approved",placeholder:"可选；不会自动从游客原文带入"})])]),
    el("div",{class:"tv-controls"},[btn("预览公开字段",preview,"preview-button"),el("label",{},[el("input",{id:"ta-model",type:"checkbox"})," 使用已配置模型（会产生用量）"]),btn("服务接待材料",()=>generate("service"),"service"),btn("营销草稿",()=>generate("marketing"),"marketing"),btn("产品创意",()=>generate("product"),"product")]),
    el("details",{id:"ta-preview-box"},[el("summary",{text:"模型请求公开字段预览"}),el("pre",{id:"ta-preview"})]),el("p",{id:"ta-status",class:"tv-status","aria-live":"polite"}),el("textarea",{id:"ta-output",rows:"18",placeholder:"交付草稿将在这里显示，可人工编辑。"}),el("div",{class:"tv-controls"},[btn("导出 Markdown",()=>exportCurrent("md"),"export-md"),btn("导出 JSON",()=>exportCurrent("json"),"export-json"),btn("打印 / 另存 PDF",()=>window.print(),"print")]),el("details",{},[el("summary",{text:"执行步骤与追溯"}),el("ol",{id:"ta-trace"})])
  ]);slot.append(panel);document.addEventListener("travel-workbench-invalidated",invalidate);document.addEventListener("travel-workbench-selection",invalidate);if(root.TravelAgentRequest)request({action:"status"}).then(x=>status(x.available?"已检测到模型配置；本地评估始终可用。":`${x.message} 本地评估与固定模板仍可用。`)).catch(error=>status(error.message,true));else status("离线模式：使用确定性评估与规则报告；需要本机服务才能建立服务端确认。");}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})(globalThis);
