(function(root){"use strict";
  const Editor=root.TravelRequestEditor,Generator=root.TravelPlanGenerator,Schema=root.TravelTaskSchema,$=id=>document.getElementById(`tc-${id}`),el=(tag,attrs={},children=[])=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==="text")n.textContent=v;else if(k==="class")n.className=v;else if(k.startsWith("on"))n.addEventListener(k.slice(2),v);else if(v!==undefined&&v!==null)n.setAttribute(k,v);}for(const c of children)n.append(c);return n;};let draft=null,draftSession=null,operation=0,editorState=null;
  const task=()=>root.TravelWorkbench.read(),load=(next,message)=>{root.TravelWorkbench.load(Schema.parse(next));document.dispatchEvent(new CustomEvent("travel-workbench-invalidated",{detail:{task:next}}));note(message||"修改已保存；旧确认与交付资格已失效。");},note=(message,error=false)=>{if($("status")){$("status").textContent=message;$("status").dataset.kind=error?"error":"info";}},input=(label,id,type="text")=>el("label",{class:"tv-field"},[el("span",{text:label}),el("input",{id:`tc-${id}`,type})]);
  function renderDiff(){const rows=draft?Editor.diff(task(),draft.payload):[];$("diff").replaceChildren(rows.length?el("table",{class:"tv-table tc-diff"},[el("thead",{},[el("tr",{},["字段","当前值","草稿值"].map(x=>el("th",{text:x})))]),el("tbody",{},rows.map(x=>el("tr",{},[el("td",{text:x.field}),el("td",{text:JSON.stringify(x.before)}),el("td",{text:JSON.stringify(x.after)})]))) ]):el("p",{class:"tv-note",text:"暂无待应用的变化。"}));$("questions").textContent=draft?.questions?.length?`待澄清：${draft.questions.join("；")}`:"";$("apply").disabled=!rows.length;}
  async function propose(useModel){try{const text=$("natural").value.trim();if(!text)throw new Error("请先输入游客需求。");note(useModel?"模型正在整理草稿……":"正在本地整理草稿……");if(useModel){if(!root.TravelAgentRequest)throw new Error("离线版不调用模型，请使用本机一键启动入口或选择本地整理。");if(!draftSession)draftSession=(await root.TravelAgentRequest({action:"new"})).sessionId;const out=await root.TravelAgentRequest({action:"extract",sessionId:draftSession,text,demo:task().demo,basePayload:task()});draft={payload:out.payload,evidence:out.evidence,questions:out.questions,mode:"model"};}else draft=Editor.localDraft(text,task());renderDiff();note(`已形成${useModel?"模型":"本地规则"}草稿，仅显示差异，尚未修改任务。`);}catch(error){note(error.message,true);}}
  function applyDraft(){if(!draft)return;load(draft.payload,"已应用需求草稿；未提及字段保持原值。");draft=null;renderDiff();}
  function renderStructured(){const r=task().request;$("windows").replaceChildren(...r.dayWindows.map(w=>el("div",{class:"tc-window"},[el("b",{text:`第 ${w.day} 天`}),input("开始",`start-${w.day}`,"time"),input("结束",`end-${w.day}`,"time"),input("最少活动",`min-${w.day}`,"number"),el("label",{class:"tv-field"},[el("span",{text:"用餐要求"}),el("input",{id:`tc-meals-${w.day}`,value:w.requiredMeals.join("、")})])])));for(const w of r.dayWindows){$(`start-${w.day}`).value=w.start;$(`end-${w.day}`).value=w.end;$(`min-${w.day}`).value=w.minActivities;}$("allergens").value=r.dietaryRequirements.excludedAllergens.join("、");$("cross").checked=r.dietaryRequirements.avoidCrossContact;for(const k of ["wheelchairRoute","stepFree","accessibleRoom","accessibleVehicle"])$(`access-${k}`).checked=r.accessibilityRequirements[k];}
  function saveStructured(){try{const next=task();next.request.dayWindows=next.request.dayWindows.map(w=>({day:w.day,start:$(`start-${w.day}`).value,end:$(`end-${w.day}`).value,minActivities:Number($(`min-${w.day}`).value),requiredMeals:$(`meals-${w.day}`).value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean)}));next.request.dietaryRequirements.excludedAllergens=$("allergens").value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean);next.request.dietaryRequirements.avoidCrossContact=$("cross").checked;for(const k of ["wheelchairRoute","stepFree","accessibleRoom","accessibleVehicle"])next.request.accessibilityRequirements[k]=$(`access-${k}`).checked;load(next,"逐日时段、饮食与无障碍约束已保存。");renderStructured();}catch(error){note(error.message,true);}}
  const resourceTemplate=t=>({id:`resource-${Date.now()}`,destinationId:t.request.destinationId,areaId:"待填写区域",name:"",type:"activity",location:"",durationMinutes:60,openStart:"09:00",openEnd:"18:00",indoor:false,tags:[],priceMode:"fixed",adultPrice:null,childPrice:null,seniorPrice:null,unitPrice:null,capacityPerSlot:null,capacityPerRoom:null,accessibleRoomsAvailable:null,allergenFree:{},crossContactControlled:{},dietSupport:{},accessibility:{wheelchairRoute:"unknown",stepFree:"unknown",accessibleRoom:"unknown",accessibleVehicle:"unknown"},pricingEvidenceIds:[],openingEvidenceIds:[],capacityEvidenceIds:[],suitabilityEvidenceIds:[]}),factTemplate=t=>({id:`fact-${Date.now()}`,resourceId:null,topic:"",text:"",sourceLabel:"",sourceUrl:null,observedAt:t.evaluationDate,validFrom:null,validTo:null,status:"unknown",demo:t.demo}),transferTemplate=t=>({id:`transfer-${Date.now()}`,fromResourceId:t.resources[0]?.id||"",toResourceId:t.resources[1]?.id||t.resources[0]?.id||"",minutes:0,walkingMinutes:0,costMode:"unknown",amount:null,serviceResourceId:null,evidenceIds:[]});
  function field(label,key,type="text",advanced=false){return el("label",{class:`tv-field${advanced?" tc-advanced":""}`},[el("span",{text:label}),el("input",{id:`tc-field-${key}`,type})]);}
  function selectField(label,key,values){return el("label",{class:"tv-field"},[el("span",{text:label}),el("select",{id:`tc-field-${key}`},values.map(([v,n])=>el("option",{value:v,text:n}))) ]);}
  function openRecord(kind,id=null,copyId=null){const t=task();let value;if(id)value=structuredClone(t[kind].find(x=>x.id===id));else if(copyId){value=structuredClone(t[kind].find(x=>x.id===copyId));value.id=`${kind.slice(0,-1)}-${Date.now()}`;if(value.name)value.name+= " 副本";}else value=kind==="resources"?resourceTemplate(t):kind==="facts"?factTemplate(t):transferTemplate(t);editorState={kind,id,value};const body=$("record-body");body.replaceChildren();const specs=kind==="resources"?[["名称","name"],["类型","type","select"],["所在区域","areaId"],["详细位置","location"],["游览/服务时长（分钟）","durationMinutes","number"],["开放开始","openStart","time"],["开放结束","openEnd","time"],["标签（顿号分隔）","tags"],["计价方式","priceMode","select"],["成人价","adultPrice","number"],["儿童价","childPrice","number"],["长者价","seniorPrice","number"],["固定/单元价","unitPrice","number"],["每时段容量","capacityPerSlot","number"],["每房容量","capacityPerRoom","number"],["无障碍房数量","accessibleRoomsAvailable","number"]]:kind==="facts"?[["关联资源","resourceId","resource"],["主题","topic"],["事实内容","text"],["来源名称","sourceLabel"],["来源网址","sourceUrl"],["采集日期","observedAt","date"],["有效开始","validFrom","date"],["有效结束","validTo","date"],["状态","status","status"]]:[["起点资源","fromResourceId","resource"],["终点资源","toResourceId","resource"],["交通分钟","minutes","number"],["步行分钟","walkingMinutes","number"],["费用方式","costMode","cost"],["金额","amount","number"],["服务资源","serviceResourceId","resource-null"],["证据 ID（顿号分隔）","evidenceIds"]];for(const [label,key,type]of specs){let node;if(type==="select")node=selectField(label,key,key==="type"?[["activity","景区/活动"],["stay","酒店"],["meal","餐饮"],["transfer","交通服务"]]:[["ticket","门票"],["per_person","按人"],["per_room_night","每房晚"],["fixed","固定"]]);else if(type==="status")node=selectField(label,key,[["unknown","待核对"],["confirmed","已确认"],["conflict","有冲突"]]);else if(type==="cost")node=selectField(label,key,[["unknown","待核对"],["included","已包含"],["fixed","固定"],["per_person","按人"]]);else if(type?.startsWith("resource")){const options=[["",type==="resource-null"?"无":"全局"],...t.resources.map(r=>[r.id,r.name])];node=selectField(label,key,options);}else node=field(label,key,type||"text");body.append(node);const control=document.getElementById(`tc-field-${key}`);const raw=value[key];control.value=Array.isArray(raw)?raw.join("、"):(raw??"");}$("record-title").textContent={resources:"资源表单",facts:"事实卡表单",transfers:"交通区间表单"}[kind];$("delete").hidden=!id;$("record-error").textContent="";$("record-dialog").showModal();}
  function saveRecord(){try{const {kind,id,value}=editorState;const specs=[...$("record-body").querySelectorAll("input,select")];for(const control of specs){const key=control.id.replace("tc-field-","");let v=control.value.trim();if(["durationMinutes","minutes","walkingMinutes"].includes(key))v=Number(v);else if(["adultPrice","childPrice","seniorPrice","unitPrice","capacityPerSlot","capacityPerRoom","accessibleRoomsAvailable","amount"].includes(key))v=v===""?null:Number(v);else if(["tags","evidenceIds"].includes(key))v=v.split(/[、,，]/).map(x=>x.trim()).filter(Boolean);else if(["resourceId","serviceResourceId","sourceUrl","validFrom","validTo"].includes(key)&&v==="")v=null;value[key]=v;}const next=task();if(id)next[kind][next[kind].findIndex(x=>x.id===id)]=value;else next[kind].push(value);load(next,"表单记录已保存。");$("record-dialog").close();}catch(error){$("record-error").textContent=error.message;}}
  function references(t,kind,id){if(kind==="resources")return[...t.facts.filter(x=>x.resourceId===id).map(x=>`事实卡 ${x.id}`),...t.transfers.filter(x=>x.fromResourceId===id||x.toResourceId===id||x.serviceResourceId===id).map(x=>`交通 ${x.id}`),...t.plans.filter(x=>x.items.some(i=>i.resourceId===id)||x.stays.some(s=>s.resourceId===id)).map(x=>`方案 ${x.id}`)];if(kind==="facts")return[...t.resources.filter(x=>[...x.pricingEvidenceIds,...x.openingEvidenceIds,...x.capacityEvidenceIds,...x.suitabilityEvidenceIds].includes(id)).map(x=>`资源 ${x.id}`),...t.transfers.filter(x=>x.evidenceIds.includes(id)).map(x=>`交通 ${x.id}`)];return[];}
  function deleteRecord(){try{const {kind,id}=editorState,t=task(),refs=references(t,kind,id);if(refs.length)throw new Error(`不能删除：仍被 ${refs.join("、")} 引用。`);if(kind==="resources"&&t.resources.length===1)throw new Error("任务至少需要一条资源。");t[kind]=t[kind].filter(x=>x.id!==id);load(t,"记录已删除。");$("record-dialog").close();}catch(error){$("record-error").textContent=error.message;}}
  function installTableEditors(){const map=[["tv-resources","resources"],["tv-facts","facts"],["tv-transfers","transfers"]];for(const [containerId,kind]of map){const box=document.getElementById(containerId);if(!box||box.dataset.contestBound)return;box.dataset.contestBound="1";box.addEventListener("click",event=>{const b=event.target.closest("button");if(!b||b.textContent!=="编辑")return;event.preventDefault();event.stopImmediatePropagation();const row=b.closest("tr"),rows=[...row.parentElement.children],index=rows.indexOf(row),id=kind==="resources"?row.querySelector("b")?.textContent.split("·")[0].trim():kind==="facts"?row.querySelector("span")?.textContent.trim():task().transfers[index]?.id;if(id)openRecord(kind,id);},true);}}
  function generate(){const own=++operation;$("cancel-gen").hidden=false;$("generate").disabled=true;note("正在构建有界候选；可随时取消……");setTimeout(()=>{if(own!==operation)return;try{const t=task(),manual=t.plans.filter(x=>x.origin==="manual"),out=Generator.generate({...t,plans:[]},{maxOutput:12});if(own!==operation)return;const next={...t,plans:[...manual,...out.plans]};load(next,`${out.message}；保留 ${manual.length} 个手工方案。${out.truncationReasons?.length?` 截断原因：${out.truncationReasons.join("、")}`:""}`);root.TravelWorkbench.analyze();}catch(error){note(error.message,true);}finally{if(own===operation){$("cancel-gen").hidden=true;$("generate").disabled=false;}}},40);}
  function cancelGenerate(){operation++;$("cancel-gen").hidden=true;$("generate").disabled=false;note("候选生成已取消，当前任务未改变。");}
  function install(){if(!root.TravelWorkbench||!Editor||$("root"))return;document.head.append(el("style",{text:".tc-card{border:1px solid #d8e4e6;border-radius:12px;padding:14px;margin:12px 0;background:#f8fbfb}.tc-diff{min-width:620px}.tc-window{display:grid;grid-template-columns:70px repeat(4,minmax(105px,1fr));gap:8px;align-items:end;border-bottom:1px solid #e5edef;padding:9px 0}.tc-record-grid{display:grid;grid-template-columns:repeat(2,minmax(160px,1fr));gap:12px}#tc-record-dialog{width:min(820px,94vw)}#tc-record-error{color:#b42318}.tc-scenarios{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tc-scenario{padding:15px;border:1px solid #c9dcdf;border-radius:12px;background:#fff}.tc-scenario b{display:block;font-size:16px}@media(max-width:760px){.tc-scenarios,.tc-record-grid{grid-template-columns:1fr}.tc-window{grid-template-columns:1fr 1fr}}"}));const main=document.querySelector("#tv-root .tv-main"),hero=main.querySelector(".tv-hero");hero.after(el("section",{class:"tc-scenarios"},[el("button",{class:"tc-scenario",onclick:()=>document.getElementById("tv-area-1").scrollIntoView({behavior:"smooth"})},[el("b",{text:"核心场景一 · 游客咨询与个性化行程"}),el("span",{text:"需求澄清 → 有据咨询 → 确定性规划 → 人工确认 → 接待材料"})]),el("button",{class:"tc-scenario",onclick:()=>document.getElementById("tv-area-4").scrollIntoView({behavior:"smooth"})},[el("b",{text:"核心场景二 · 文旅营销与产品创意"}),el("span",{text:"确认方案 → 公开字段预览 → 渠道化创作 → 人工编辑 → 安全导出"})])]));
    const area2=document.getElementById("tv-area-2");
    area2.querySelector("h2").after(el("div",{class:"tc-card"},[
      el("h3",{text:"用自然语言整理游客需求"}),
      el("textarea",{id:"tc-natural",rows:"4",placeholder:"例：7月18日到云水古城玩2天，2名成人、1名儿童和1名长者，预算3000元；首日16点抵达，花生过敏，需要无台阶路线。"}),
      el("div",{class:"tv-controls"},[
        el("button",{onclick:()=>propose(false),text:"本地整理草稿"}),
        el("button",{onclick:()=>propose(true),text:"使用模型整理草稿"}),
        el("button",{id:"tc-apply",class:"primary",onclick:applyDraft,text:"应用所选草稿",disabled:""})
      ]),el("p",{id:"tc-questions",class:"tv-status"}),el("div",{id:"tc-diff",class:"tv-scroll"})
    ]));
    const basic=document.getElementById("tv-form");
    const accessControls=[["wheelchairRoute","需要轮椅路线"],["stepFree","需要无台阶通行"],["accessibleRoom","需要无障碍客房"],["accessibleVehicle","需要无障碍车辆"]].map(([k,n])=>el("label",{},[el("input",{id:`tc-access-${k}`,type:"checkbox"}),` ${n}`]));
    basic.after(el("details",{class:"tc-card",open:""},[
      el("summary",{text:"逐日时段、饮食与无障碍约束"}),el("div",{id:"tc-windows"}),
      el("div",{class:"tv-grid-2"},[input("排除过敏原（顿号分隔）","allergens"),el("label",{class:"tv-field"},[el("span",{text:"饮食安全"}),el("span",{},[el("input",{id:"tc-cross",type:"checkbox"})," 需避免交叉接触"])])]),
      el("div",{class:"tv-controls"},[...accessControls,el("button",{class:"primary",onclick:saveStructured,text:"保存结构化约束"})])
    ]));
    const oldGen=document.getElementById("tv-generate-plans");oldGen.hidden=true;oldGen.after(el("button",{id:"tc-generate",onclick:generate,text:"生成并保留手工方案"}),el("button",{id:"tc-cancel-gen",onclick:cancelGenerate,text:"取消生成",hidden:""}));
    const area5=document.getElementById("tv-area-5"),toolbar=area5.querySelector(".tv-toolbar > div");[...toolbar.children].slice(0,4).forEach(x=>x.hidden=true);toolbar.prepend(el("button",{onclick:()=>openRecord("resources"),text:"新增资源（表单）"}),el("button",{onclick:()=>{const id=task().resources[0]?.id;if(id)openRecord("resources",null,id);},text:"复制首条资源"}),el("button",{onclick:()=>openRecord("facts"),text:"新增事实卡"}),el("button",{onclick:()=>openRecord("transfers"),text:"新增交通区间"}));area5.append(el("details",{class:"tc-card"},[el("summary",{text:"高级工具与数据说明"}),el("p",{text:"JSON 仅用于技术人员批量导入导出。日常维护请使用上方中文表单；空白新增在保存前不会写入任务。"})]));
    document.body.append(el("dialog",{id:"tc-record-dialog"},[el("h2",{id:"tc-record-title"}),el("div",{id:"tc-record-body",class:"tc-record-grid"}),el("p",{id:"tc-record-error"}),el("div",{class:"tv-toolbar"},[el("div",{},[el("button",{class:"primary",onclick:saveRecord,text:"保存"}),el("button",{id:"tc-delete",onclick:deleteRecord,text:"删除"})]),el("button",{onclick:()=>$("record-dialog").close(),text:"取消"})])]),el("p",{id:"tc-status",class:"tv-status","aria-live":"polite"}));renderDiff();renderStructured();installTableEditors();new MutationObserver(installTableEditors).observe(area5,{childList:true,subtree:true});document.addEventListener("travel-workbench-invalidated",()=>{draft=null;renderDiff();renderStructured();});}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(install,0));else setTimeout(install,0);
})(globalThis);
