(function(root){
  "use strict";
  const Schema=typeof module==="object"&&module.exports?require("./task-schema.js"):root.TravelTaskSchema;
  const allowedKinds=new Set(["service","marketing","product"]),safe=value=>String(value??"").replace(/[<>\r\n]/g," "),time=value=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;
  function selectedRow(result,id){const row=result.rows.find(x=>x.id===id);if(!row)throw new Error("选定方案不存在");return row;}
  function normalizeOptions(options={}){return{channel:safe(options.channel||"公众号"),audience:safe(options.audience||"文旅兴趣人群"),length:safe(options.length||"中等"),theme:safe(options.theme||"在地体验"),approvedPublicText:safe(options.approvedPublicText||"")};}
  function publicProjection(task,result,selectedPlanId,options={}){const row=selectedRow(result,selectedPlanId),ids=new Set(row.evidenceIds),resources=new Map(task.resources.map(x=>[x.id,x]));return{
    destination:{id:task.request.destinationId,name:task.request.destination},
    campaign:normalizeOptions(options),
    travel:{days:task.request.days,partySize:task.request.adults+task.request.children+task.request.seniors,interests:[...task.request.interests]},
    plan:{id:row.id,name:row.name,status:row.status,knownSubtotal:row.totals.knownSubtotal,priceComplete:row.totals.priceComplete,matchedInterests:row.matchedInterests,schedule:row.schedule.filter(x=>x.kind==="item").map(x=>{const r=resources.get(x.resourceId);return{resourceId:x.resourceId,name:x.name,type:x.type,day:x.day,start:time(x.start),end:time(x.end),location:x.location,tags:r?.tags||[]};})},
    factReferences:task.facts.filter(x=>ids.has(x.id)).map(x=>({id:x.id,resourceId:x.resourceId,topic:x.topic,sourceLabel:x.sourceLabel,observedAt:x.observedAt,validFrom:x.validFrom,validTo:x.validTo,status:x.status,demo:x.demo})),
    privacy:{excluded:["游客原文","聊天记录","饮食原文","无障碍原文","API Key","个人联系方式"]},demo:task.demo
  };}
  const marketingProjection=publicProjection;
  function heading(kind){return{service:"服务接待执行单",marketing:"文旅营销内容草稿",product:"特色文创与服务产品创意"}[kind];}
  function disclaimer(task){return task.demo?"> 模拟实训材料：地点、价格和能力均为虚构，不代表真实可订、已上线或已发布。":"> 内部待审草稿：开放、价格、库存、服务能力及对外表述须在执行或发布前人工复核。";}
  function serviceTemplate(task,row){const lines=["## 接待目标","",`为 ${safe(task.request.destination)} 行程提供可执行的到访、用餐与衔接提示。`,`同行构成：成人 ${task.request.adults}、儿童 ${task.request.children}、长者 ${task.request.seniors}；已知预算 ¥${task.request.budget.toFixed(2)}。`,"","## 分日接待日程",""];for(const x of row.schedule.filter(x=>x.kind==="item"))lines.push(`- 第${x.day}天 ${time(x.start)}–${time(x.end)}｜${safe(x.name)}｜${safe(x.location)}`);lines.push("","## 岗位执行清单","","- 出发前：逐项复核开放时间、容量、价格、交通和服务能力。","- 到访前：将饮食与无障碍结构化约束交由对应岗位人工确认。","- 衔接时：以任务中的显式交通分钟为准，遇到延误应重新评估。","- 完成后：仅记录必要的服务结果，不写入联系方式或敏感原文。","","## 风险与待确认","",...(row.reasons.length?row.reasons.map(x=>`- ${safe(x)}`):["- 当前确定性规则未发现已录入条件冲突，但实时状态仍须人工确认。"]),"- 系统不会自动联系商户、预订、付款或提交数据。");return lines;}
  function marketingTemplate(task,row,options){const o=normalizeOptions(options),base=`${safe(task.request.destination)} · ${safe(row.matchedInterests.join("、")||o.theme)}`;const lines=[`渠道：${o.channel}`,`目标受众：${o.audience}`,`主题：${o.theme}`,`篇幅：${o.length}`,"","## 发布前定位","",`${base}，以已确认行程中的可公开地点与体验节点为素材。`];if(/短视频|视频/.test(o.channel))lines.push("","## 分镜脚本","","1. 开场 3 秒：目的地与主题钩子。","2. 中段：按日程顺序展示 2–3 个体验节点，不展示个人约束。","3. 收束：提示开放、价格和服务状态以出行前人工核验为准。","","## 画面与字幕","",`- 主视觉：${safe(o.theme)}；字幕面向 ${safe(o.audience)}。`);else if(/公众号|长文/.test(o.channel))lines.push("","## 标题建议","",`${base}：一份可核验的行程灵感`,"","## 正文结构","","- 为什么值得体验：从已确认兴趣标签切入。","- 怎么安排：按分日日程概述，不承诺实时库存。","- 出行提示：列出需人工复核的信息。");else lines.push("","## 社交平台短文案","",`${base} 行程灵感：把景区、旅居与餐饮节点串成一条清晰路线。开放、价格及服务能力请在出发前复核。`,"","## 互动引导","","- 你更偏好文化体验、亲子互动还是在地美食？");if(o.approvedPublicText)lines.push("","## 人工批准的公开补充","",o.approvedPublicText);lines.push("","## 发布门槛","","- 草稿未自动发布；发布前须人工核对事实引用、版权、敏感信息与渠道规范。");return lines;}
  function productTemplate(task,row,options){const o=normalizeOptions(options);return["## 创意命题","",`围绕“${o.theme}”为 ${o.audience} 设计可组合的在地体验或文创服务。`,"","## 概念方案","",`- 核心载体：从 ${safe(row.matchedInterests.join("、")||"在地文化")} 节点提炼可教学、可体验的模块。`,`- 场景组合：将 ${safe(row.schedule.filter(x=>x.kind==="item").slice(0,3).map(x=>x.name).join(" → "))} 串联为体验路径。`,`- 渠道表达：优先适配 ${o.channel}，篇幅为 ${o.length}。`,"","## 最小试用设计","","1. 先制作纸面或数字原型，不宣称已经上线。","2. 邀请内部体验者按统一记录表反馈清晰度、兴趣度与执行难点。","3. 只依据匿名汇总反馈迭代，不收集无关个人信息。","","## 未验证假设","","- 市场需求、生产成本、版权授权、实时库存、上线状态和商业回报均未验证。","- 若涉及真实销售、联系商户、上传或发布，必须另行取得明确授权。"];
  }
  function template(kind,task,row,options={}){const lines=[`# ${heading(kind)}`,"",disclaimer(task),"",`方案：${safe(row.id)} · ${safe(row.name)}`,`规则状态：${safe(row.statusLabel)}`,`已知费用：¥${row.totals.knownSubtotal.toFixed(2)}${row.totals.priceComplete?"":"（总价不完整）"}`,""];lines.push(...(kind==="service"?serviceTemplate(task,row):kind==="marketing"?marketingTemplate(task,row,options):productTemplate(task,row,options)));return lines.join("\n");}
  function create({kind,task,result,confirmation,options={},content=null,generationMode}){if(!allowedKinds.has(kind))throw new Error("不支持的交付物类型");const parsed=Schema.parse(task);if(!confirmation||confirmation.taskHash!==Schema.hash(parsed)||confirmation.taskHash!==result.taskHash)throw new Error("确认快照已过期");const row=selectedRow(result,confirmation.selectedPlanId);if(row.status!=="eligible")throw new Error("只有通过已录入条件校验的当前方案可生成交付物");const normalized=normalizeOptions(options);return{kind,taskHash:result.taskHash,confirmationId:confirmation.confirmationId,selectedPlanId:confirmation.selectedPlanId,sourceFactIds:[...row.evidenceIds],engineVersion:result.engineVersion,createdAt:new Date().toISOString(),demo:parsed.demo,expired:false,generationMode:generationMode||(content?"configured-model":"fixed-template"),options:normalized,content:content||template(kind,parsed,row,normalized)};}
  function toMarkdown(item){return`${item.content}\n\n---\n确认 ID：${safe(item.confirmationId)}；任务哈希：${safe(item.taskHash)}；方案：${safe(item.selectedPlanId)}；生成方式：${safe(item.generationMode)}；模拟：${item.demo?"是":"否"}；过期：${item.expired?"是":"否"}\n`;}
  const api={create,template,publicProjection,marketingProjection,normalizeOptions,toMarkdown};if(typeof module==="object"&&module.exports)module.exports=api;else root.TravelDeliverables=api;
})(globalThis);
