(function(root){
  "use strict";
  const Core=typeof module==="object"&&module.exports?require("./travel-core.js"):root.TravelCore;
  const tokenize=text=>[...new Set(String(text||"").toLowerCase().split(/[\s,，。；;：:、？?！!（）()\[\]{}]+/).flatMap(x=>x.length>2?[x,...Array.from(x)]:[x]).filter(Boolean))];
  function consult(task,question,{resourceId=null,topic=null,max=8}={}){
    const query=tokenize(question),resources=new Map(task.resources.map(x=>[x.id,x])),scored=[];
    for(const fact of task.facts){if(resourceId&&fact.resourceId!==resourceId)continue;if(topic&&fact.topic!==topic)continue;const resource=fact.resourceId?resources.get(fact.resourceId):null,hay=`${fact.topic} ${fact.text} ${fact.sourceLabel} ${resource?.name||""}`.toLowerCase();let score=resourceId&&fact.resourceId===resourceId?20:0;for(const token of query){if(resource?.name?.toLowerCase().includes(token))score+=8;if(fact.topic.toLowerCase().includes(token))score+=5;if(hay.includes(token))score+=2;}if(score>0||(!query.length&&resourceId))scored.push({fact,resource,score});}
    scored.sort((a,b)=>b.score-a.score||a.fact.id.localeCompare(b.fact.id));const cards=scored.slice(0,Math.min(8,max)).map(({fact,resource})=>({factId:fact.id,resourceId:fact.resourceId,resourceName:resource?.name||null,topic:fact.topic,text:fact.text,sourceLabel:fact.sourceLabel,sourceUrl:fact.sourceUrl,observedAt:fact.observedAt,validFrom:fact.validFrom,validTo:fact.validTo,status:fact.status,validity:Core.validity(fact,task),demo:fact.demo})),valid=cards.filter(x=>x.validity==="valid"),conflicts=cards.filter(x=>x.validity==="conflict"),expired=cards.filter(x=>["expired","not-yet-valid"].includes(x.validity));let state="unknown",summary="没有命中本地资料；请补充事实卡或明确资源。";if(conflicts.length){state="conflict";summary="命中互相冲突的资料，系统不替代人工选择。";}else if(valid.length){state="grounded";summary=`命中 ${valid.length} 条当前有效的本地资料。`;}else if(expired.length){state="expired";summary="仅命中过期或尚未生效的资料，不能据此作肯定结论。";}return{question:String(question||"").slice(0,1000),state,summary,cards,citations:valid.map(x=>x.factId),unknowns:state==="grounded"?[]:[summary],conflicts:conflicts.map(x=>x.factId),suggestedQuestions:cards.length?["需要核对哪个日期的适用性？","是否要补充来源和确认日期？"]:["请指定资源名称或资料主题。"]};
  }
  function validateModelAnswer(answer,cards){const allowed=new Set(cards.map(x=>x.factId)),citations=Array.isArray(answer?.citations)?answer.citations:[],invalid=citations.filter(x=>!allowed.has(x));return{valid:invalid.length===0,answer:typeof answer?.answer==="string"?answer.answer:"",citations:citations.filter(x=>allowed.has(x)),invalidCitations:invalid,unknowns:Array.isArray(answer?.unknowns)?answer.unknowns:[],conflicts:Array.isArray(answer?.conflicts)?answer.conflicts:[],suggestedQuestions:Array.isArray(answer?.suggestedQuestions)?answer.suggestedQuestions:[]};}
  const api={consult,validateModelAnswer,tokenize};if(typeof module==="object"&&module.exports)module.exports=api;else root.TravelKnowledge=api;
})(globalThis);
