(function(root){
  "use strict";
  const Schema=typeof module==="object"&&module.exports?require("./task-schema.js"):root.TravelTaskSchema;
  const ENGINE_VERSION="4.2.0";
  const statusLabels={eligible:"通过已录入条件校验",pending:"待核实",rejected:"不满足"};
  const clock=value=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;
  const safe=value=>String(value??"").replace(/[<>|\r\n]/g," ");
  const cents=value=>value===null?null:Math.round(value*100);
  const yuan=value=>value===null?null:value/100;
  function issue(code,severity,message,detail={}){return{code,severity,...detail,message,evidenceIds:detail.evidenceIds||[]};}
  function validity(fact,task){
    if(!fact)return"missing";
    if(fact.status!=="confirmed")return fact.status;
    const when=task.request.startDate||task.evaluationDate;
    if(!task.demo&&!task.request.startDate)return"missing-date";
    if(fact.validFrom&&when<fact.validFrom)return"not-yet-valid";
    if(fact.validTo&&when>fact.validTo)return"expired";
    return"valid";
  }
  function evidenceIssues(ids,task,factMap,domain,detail={}){
    if(!ids.length)return[issue("EVIDENCE_MISSING","pending",`${domain}缺少资料事实引用`,{...detail,field:domain})];
    const out=[];
    for(const id of ids){const fact=factMap.get(id),state=validity(fact,task);if(state!=="valid")out.push(issue(`EVIDENCE_${state.toUpperCase().replaceAll("-","_")}`,"pending",`${domain}资料 ${id} 状态为${({missing:"缺失",unknown:"未知",conflict:"冲突","missing-date":"真实任务缺少适用日期","not-yet-valid":"尚未生效",expired:"已过期"})[state]||state}`,{...detail,field:domain,evidenceIds:[id]}));}
    return out;
  }
  function pricing(resource,people,quantity,nights=1){
    const times=quantity*nights,unknown=[];let value=0,formula="";
    if(resource.priceMode==="ticket"){
      for(const [key,count,label] of [["adultPrice",people.adults,"成人"],["childPrice",people.children,"儿童"],["seniorPrice",people.seniors,"长者"]]){if(count&&resource[key]===null)unknown.push(`${label}票价`);else value+=(cents(resource[key]||0))*count*quantity;}
      formula=`成人/儿童/长者单价 × 对应人数 × ${quantity}次`;
    }else if(resource.priceMode==="per_person"){
      if(resource.unitPrice===null)unknown.push("人均价");else value=cents(resource.unitPrice)*people.total*quantity;formula=`¥${resource.unitPrice??"?"} × ${people.total}人 × ${quantity}次`;
    }else if(resource.priceMode==="per_room_night"){
      if(resource.unitPrice===null)unknown.push("每房晚价");else value=cents(resource.unitPrice)*quantity*nights;formula=`¥${resource.unitPrice??"?"} × ${quantity}间 × ${nights}晚`;
    }else{
      if(resource.unitPrice===null)unknown.push("固定服务价");else value=cents(resource.unitPrice)*times;formula=`¥${resource.unitPrice??"?"} × ${times}`;
    }
    if(!Number.isSafeInteger(value))throw new Error(`${resource.name}金额超出安全范围`);
    return{knownCents:value,complete:!unknown.length,unknown,formula};
  }
  function checkSuitability(resource,task,detail){
    const out=[],req=task.request;
    if(resource.type==="meal"){
      for(const allergen of req.dietaryRequirements.excludedAllergens){const state=resource.allergenFree[allergen]||"unknown";out.push(...state==="yes"?[]:[issue(state==="no"?"ALLERGEN_CONFLICT":"ALLERGEN_UNKNOWN",state==="no"?"hard":"pending",`${resource.name} 对“${allergen}”的排除能力为 ${state}`,{...detail,resourceId:resource.id,field:`allergenFree.${allergen}`,evidenceIds:resource.suitabilityEvidenceIds})]);if(req.dietaryRequirements.avoidCrossContact){const cross=resource.crossContactControlled[allergen]||"unknown";if(cross!=="yes")out.push(issue(cross==="no"?"CROSS_CONTACT_CONFLICT":"CROSS_CONTACT_UNKNOWN",cross==="no"?"hard":"pending",`${resource.name} 对“${allergen}”的交叉接触控制为 ${cross}`,{...detail,resourceId:resource.id,field:`crossContactControlled.${allergen}`,evidenceIds:resource.suitabilityEvidenceIds}));}}
      for(const diet of req.dietaryRequirements.dietTypes){const state=resource.dietSupport[diet]||"unknown";if(state!=="yes")out.push(issue(state==="no"?"DIET_CONFLICT":"DIET_UNKNOWN",state==="no"?"hard":"pending",`${resource.name} 对“${diet}”餐型支持为 ${state}`,{...detail,resourceId:resource.id,field:`dietSupport.${diet}`,evidenceIds:resource.suitabilityEvidenceIds}));}
    }
    const checks=[];if(["activity","meal","stay"].includes(resource.type)){if(req.accessibilityRequirements.wheelchairRoute)checks.push("wheelchairRoute");if(req.accessibilityRequirements.stepFree)checks.push("stepFree");}if(resource.type==="stay"&&req.accessibilityRequirements.accessibleRoom)checks.push("accessibleRoom");if(resource.type==="transfer"&&req.accessibilityRequirements.accessibleVehicle)checks.push("accessibleVehicle");
    for(const key of checks){const state=resource.accessibility[key]||"unknown";if(state!=="yes")out.push(issue(state==="no"?"ACCESSIBILITY_CONFLICT":"ACCESSIBILITY_UNKNOWN",state==="no"?"hard":"pending",`${resource.name} 的 ${key} 能力为 ${state}`,{...detail,resourceId:resource.id,field:`accessibility.${key}`,evidenceIds:resource.suitabilityEvidenceIds}));}
    return out;
  }
  function evaluatePlan(plan,task,maps){
    const {resources,facts,transfers}=maps,req=task.request,people={adults:req.adults,children:req.children,seniors:req.seniors};people.total=people.adults+people.children+people.seniors;
    const issues=[],schedule=[],costItems=[],evidence=new Set(),walkingByDay=new Map(),interest=new Set(),usedTransferServices=new Set();let known=0,priceComplete=true;
    const addCost=(resource,calc,detail)=>{known+=calc.knownCents;priceComplete&&=calc.complete;costItems.push({resourceId:resource.id,name:resource.name,...detail,formula:calc.formula,subtotal:yuan(calc.knownCents),complete:calc.complete,evidenceIds:resource.pricingEvidenceIds});for(const x of resource.pricingEvidenceIds)evidence.add(x);for(const x of calc.unknown)issues.push(issue("PRICE_UNKNOWN","pending",`${resource.name}${x}缺失`,{resourceId:resource.id,field:"pricing",evidenceIds:resource.pricingEvidenceIds}));issues.push(...evidenceIssues(resource.pricingEvidenceIds,task,facts,`${resource.name}价格`,{resourceId:resource.id}));};
    for(const item of plan.items){const resource=resources.get(item.resourceId),detail={resourceId:resource.id,itemId:item.itemId,day:item.day},start=Schema.minutes(item.start),end=start+resource.durationMinutes,window=req.dayWindows.find(x=>x.day===item.day);for(const id of [...resource.openingEvidenceIds,...resource.capacityEvidenceIds,...resource.suitabilityEvidenceIds])evidence.add(id);
      if(start<Schema.minutes(resource.openStart)||end>Schema.minutes(resource.openEnd))issues.push(issue("OPENING_CONFLICT","hard",`${resource.name}安排 ${item.start}–${clock(end)} 超出开放时段`,detail));
      if(start<Schema.minutes(window.start)||end>Schema.minutes(window.end))issues.push(issue("DAY_WINDOW_CONFLICT","hard",`${resource.name}超出第${item.day}天可用时段`,detail));
      if(req.weather==="rain"&&req.avoidOutdoorInRain&&!resource.indoor)issues.push(issue("RAIN_OUTDOOR_CONFLICT","hard",`${resource.name}为户外项目，不满足雨天避户外要求`,detail));
      if(resource.capacityPerSlot===null)issues.push(issue("CAPACITY_UNKNOWN","pending",`${resource.name}单时段容量未知`,{...detail,field:"capacityPerSlot",evidenceIds:resource.capacityEvidenceIds}));else if(resource.capacityPerSlot<people.total)issues.push(issue("CAPACITY_CONFLICT","hard",`${resource.name}容量 ${resource.capacityPerSlot} 小于同行 ${people.total} 人`,detail));
      issues.push(...evidenceIssues(resource.openingEvidenceIds,task,facts,`${resource.name}开放时间`,detail),...evidenceIssues(resource.capacityEvidenceIds,task,facts,`${resource.name}容量`,detail),...evidenceIssues(resource.suitabilityEvidenceIds,task,facts,`${resource.name}适配条件`,detail),...checkSuitability(resource,task,detail));
      const calc=pricing(resource,people,item.quantity);addCost(resource,calc,{kind:"item",itemId:item.itemId,quantity:item.quantity});
      for(const tag of resource.tags)if(req.interests.includes(tag))interest.add(tag);
      schedule.push({kind:"item",itemId:item.itemId,resourceId:resource.id,name:resource.name,type:resource.type,day:item.day,start,end,quantity:item.quantity,mealSlot:item.mealSlot,location:resource.location});
    }
    const requiredNights=new Set(req.requiredNights),covered=new Set();
    for(const stay of plan.stays){const resource=resources.get(stay.resourceId),nights=stay.checkoutDay-stay.checkInDay,detail={resourceId:resource.id,day:stay.checkInDay};for(let night=stay.checkInDay;night<stay.checkoutDay;night++)covered.add(night);if(resource.type!=="stay")issues.push(issue("STAY_TYPE_INVALID","hard",`${resource.name}不是住宿资源`,detail));if(resource.capacityPerRoom===null)issues.push(issue("ROOM_CAPACITY_UNKNOWN","pending",`${resource.name}每间容量未知`,{...detail,field:"capacityPerRoom"}));else if(resource.capacityPerRoom*stay.rooms<people.total)issues.push(issue("ROOM_CAPACITY_CONFLICT","hard",`${stay.rooms}间${resource.name}仅覆盖 ${resource.capacityPerRoom*stay.rooms} 人，同行共 ${people.total} 人`,detail));if(req.accessibilityRequirements.accessibleRoom&&(resource.accessibleRoomsAvailable===null||resource.accessibleRoomsAvailable<stay.rooms))issues.push(issue(resource.accessibleRoomsAvailable===null?"ACCESSIBLE_ROOM_UNKNOWN":"ACCESSIBLE_ROOM_CAPACITY_CONFLICT",resource.accessibleRoomsAvailable===null?"pending":"hard",`${resource.name}无障碍房间数量${resource.accessibleRoomsAvailable===null?"未知":`仅 ${resource.accessibleRoomsAvailable} 间`}`,detail));issues.push(...evidenceIssues(resource.capacityEvidenceIds,task,facts,`${resource.name}房型容量`,detail),...checkSuitability(resource,task,detail));addCost(resource,pricing(resource,people,stay.rooms,nights),{kind:"stay",rooms:stay.rooms,nights});schedule.push({kind:"stay",resourceId:resource.id,name:resource.name,type:"stay",day:stay.checkInDay,start:Schema.minutes(stay.checkInTime),end:Schema.minutes(stay.checkInTime)+resource.durationMinutes,rooms:stay.rooms,nights,location:resource.location});}
    for(const night of requiredNights)if(!covered.has(night))issues.push(issue("STAY_NIGHT_MISSING","pending",`第${night}晚缺少住宿安排`,{day:night}));
    for(const item of req.unresolvedRequirements)issues.push(issue("REQUIREMENT_UNRESOLVED","pending",`${item.text}：${item.reason}`,{field:"unresolvedRequirements"}));
    for(let day=1;day<=req.days;day++){
      const window=req.dayWindows.find(x=>x.day===day),normal=schedule.filter(x=>x.kind==="item"&&x.day===day).sort((a,b)=>a.start-b.start||a.itemId.localeCompare(b.itemId)),activityCount=normal.filter(x=>x.type==="activity").length;
      if(activityCount<window.minActivities)issues.push(issue("DAY_ACTIVITY_GAP","hard",`第${day}天仅 ${activityCount} 项活动，少于要求 ${window.minActivities} 项`,{day}));
      for(const meal of window.requiredMeals)if(!normal.some(x=>x.type==="meal"&&x.mealSlot===meal))issues.push(issue("MEAL_GAP","hard",`第${day}天缺少 ${meal} 餐饮安排`,{day,field:`requiredMeals.${meal}`}));
      let walking=0;for(let i=1;i<normal.length;i++){const prev=normal[i-1],current=normal[i];if(current.start<prev.end){issues.push(issue("SCHEDULE_OVERLAP","hard",`第${day}天 ${prev.name} 与 ${current.name} 时间重叠`,{day,itemId:current.itemId}));continue;}if(prev.resourceId===current.resourceId)continue;const edge=transfers.get(`${prev.resourceId}->${current.resourceId}`);if(!edge){issues.push(issue("TRANSFER_MISSING","pending",`第${day}天 ${prev.name} 至 ${current.name} 缺少交通记录`,{day,itemId:current.itemId,field:"transfer"}));continue;}for(const id of edge.evidenceIds)evidence.add(id);issues.push(...evidenceIssues(edge.evidenceIds,task,facts,`${prev.name}至${current.name}交通`,{day,itemId:current.itemId}));if(req.accessibilityRequirements.accessibleVehicle){if(edge.serviceResourceId&&resources.has(edge.serviceResourceId))issues.push(...checkSuitability(resources.get(edge.serviceResourceId),task,{day,resourceId:edge.serviceResourceId}));else issues.push(issue("ACCESSIBLE_VEHICLE_UNKNOWN","pending",`${prev.name}至${current.name}未绑定已确认的无障碍车辆服务`,{day,field:"accessibility.accessibleVehicle",evidenceIds:edge.evidenceIds}));}if(current.start-prev.end<edge.minutes)issues.push(issue("TRANSFER_TIME_CONFLICT","hard",`第${day}天前往 ${current.name} 的交通缓冲不足`,{day,itemId:current.itemId,evidenceIds:edge.evidenceIds}));walking+=edge.walkingMinutes;if(edge.costMode==="unknown"){priceComplete=false;issues.push(issue("TRANSFER_PRICE_UNKNOWN","pending",`${prev.name}至${current.name}交通费用未知`,{day,evidenceIds:edge.evidenceIds}));}else if(edge.costMode!=="included"){let edgeCents=cents(edge.amount||0)*(edge.costMode==="per_person"?people.total:1);known+=edgeCents;costItems.push({kind:"transfer",resourceId:edge.serviceResourceId,name:`${prev.name} → ${current.name}`,formula:edge.costMode==="per_person"?`¥${edge.amount} × ${people.total}人`:`¥${edge.amount}`,subtotal:yuan(edgeCents),complete:true,evidenceIds:edge.evidenceIds});}if(edge.serviceResourceId){if(plan.items.some(x=>x.resourceId===edge.serviceResourceId))issues.push(issue("TRANSFER_DUPLICATE_CHARGE","hard",`交通服务 ${edge.serviceResourceId} 同时作为项目与区间计费`,{day,resourceId:edge.serviceResourceId}));usedTransferServices.add(edge.serviceResourceId);}schedule.push({kind:"transfer",transferId:edge.id,fromResourceId:prev.resourceId,toResourceId:current.resourceId,day,start:prev.end,end:prev.end+edge.minutes,walkingMinutes:edge.walkingMinutes});}
      walkingByDay.set(day,walking);if(walking>req.maxWalkingMinutes)issues.push(issue("WALKING_LIMIT_CONFLICT","hard",`第${day}天预计步行 ${walking} 分钟，超过上限 ${req.maxWalkingMinutes} 分钟`,{day}));
    }
    if(yuan(known)>req.budget)issues.push(issue("BUDGET_CONFLICT","hard",`已知费用 ¥${yuan(known).toFixed(2)} 超过预算 ¥${req.budget.toFixed(2)}`,{field:"budget"}));
    const hard=issues.some(x=>x.severity==="hard"),pending=issues.some(x=>x.severity==="pending"),status=hard?"rejected":pending?"pending":"eligible",walkValues=Array.from({length:req.days},(_,i)=>walkingByDay.get(i+1)||0);
    return{id:plan.id,name:plan.name,origin:plan.origin,status,statusLabel:statusLabels[status],issues,reasons:issues.map(x=>x.message),totals:{knownSubtotal:yuan(known),priceComplete,unknownCostCount:issues.filter(x=>/PRICE_UNKNOWN/.test(x.code)).length,total:priceComplete?yuan(known):null},total:priceComplete?yuan(known):yuan(known),walkingMinutes:walkValues.reduce((a,b)=>a+b,0),maxDayWalking:Math.max(0,...walkValues),matchedInterests:[...interest].sort(),activityCoverage:new Set(schedule.filter(x=>x.type==="activity").map(x=>x.resourceId)).size,schedule:schedule.sort((a,b)=>a.day-b.day||a.start-b.start||String(a.itemId||a.transferId||"").localeCompare(String(b.itemId||b.transferId||""))),costItems,evidenceIds:[...evidence].sort(),source:plan.source};
  }
  function evaluate(input){const migration=Schema.migrateV1(input),task=migration.task,resources=new Map(task.resources.map(x=>[x.id,x])),facts=new Map(task.facts.map(x=>[x.id,x])),transfers=new Map();for(const edge of task.transfers){const key=`${edge.fromResourceId}->${edge.toResourceId}`;if(transfers.has(key))throw new Error(`transfers: 区间重复 ${key}`);transfers.set(key,edge);}const rows=task.plans.map(plan=>evaluatePlan(plan,task,{resources,facts,transfers}));if(migration.migrated)for(const row of rows){row.issues.push(issue("MIGRATION_INCOMPLETE","pending","旧任务迁移尚未完成人工核对"));if(row.status==="eligible")row.status="pending";row.statusLabel=statusLabels[row.status];row.reasons=row.issues.map(x=>x.message);}const eligible=rows.filter(x=>x.status==="eligible"),complete=eligible.filter(x=>x.totals.priceComplete),byPrice=(a,b)=>a.totals.total-b.totals.total||a.walkingMinutes-b.walkingMinutes||a.id.localeCompare(b.id),byEase=(a,b)=>a.maxDayWalking-b.maxDayWalking||a.walkingMinutes-b.walkingMinutes||(a.totals.total??Infinity)-(b.totals.total??Infinity)||a.id.localeCompare(b.id),byExperience=(a,b)=>b.matchedInterests.length-a.matchedInterests.length||b.activityCoverage-a.activityCoverage||a.walkingMinutes-b.walkingMinutes||(a.totals.total??Infinity)-(b.totals.total??Infinity)||a.id.localeCompare(b.id);const cheapest=[...complete].sort(byPrice)[0]?.id||null,easiest=[...eligible].sort(byEase)[0]?.id||null,bestMatch=[...eligible].sort(byExperience)[0]?.id||null,pareto=complete.filter(row=>!complete.some(other=>other.totals.total<=row.totals.total&&other.walkingMinutes<=row.walkingMinutes&&(other.totals.total<row.totals.total||other.walkingMinutes<row.walkingMinutes))).map(x=>x.id);return{schemaVersion:2,engineVersion:ENGINE_VERSION,taskHash:Schema.hash(task),evaluatedAt:`${task.evaluationDate}T00:00:00.000Z`,evaluationDate:task.evaluationDate,demo:task.demo,request:task.request,rows,cheapest,easiest,bestMatch,pareto,totals:{plans:rows.length,eligible:eligible.length,pending:rows.filter(x=>x.status==="pending").length,rejected:rows.filter(x=>x.status==="rejected").length},summary:{eligible:eligible.length,pending:rows.filter(x=>x.status==="pending").length,rejected:rows.filter(x=>x.status==="rejected").length},migrationWarnings:migration.migrationWarnings,notice:"结果仅表示通过当前已录入条件校验，不代表实时可订、已预订或服务承诺；出行前须人工复核。"};}
  function report(result){const lines=["# 旅策协同 · 文旅方案诊断报告","",result.demo?"**模拟实训数据：地点、价格和服务条件均为虚构。**":"**业务草案：仅依据已录入资料，执行前须复核。**","",`任务哈希：${safe(result.taskHash)}；规则引擎：${safe(result.engineVersion)}；评测日期：${safe(result.evaluationDate)}`,`最低完整费用：${safe(result.cheapest||"无")}; 最少步行：${safe(result.easiest||"无")}; 兴趣匹配：${safe(result.bestMatch||"无")}`,"","| 方案 | 状态 | 已知小计 | 总价完整 | 步行 |","|---|---|---:|---|---:|"];for(const row of result.rows)lines.push(`| ${safe(row.id)} · ${safe(row.name)} | ${safe(row.statusLabel)} | ¥${row.totals.knownSubtotal.toFixed(2)} | ${row.totals.priceComplete?"是":"否"} | ${row.walkingMinutes} 分钟 |`);for(const row of result.rows){lines.push("",`## ${safe(row.id)} · ${safe(row.name)}`,"");for(const item of row.schedule.filter(x=>x.kind==="item"))lines.push(`- 第${item.day}天 ${clock(item.start)}–${clock(item.end)}：${safe(item.name)}（${safe(item.location)}）`);if(row.issues.length)for(const x of row.issues)lines.push(`- [${x.severity==="hard"?"不满足":"待核实"}] ${safe(x.code)}：${safe(x.message)}`);else lines.push("- 已通过当前已录入条件校验；仍不代表实时可订。");lines.push("",...row.costItems.map(x=>`- 费用：${safe(x.name)}；${safe(x.formula)}；小计 ¥${x.subtotal.toFixed(2)}${x.complete?"":"（不完整）"}`));}lines.push("","## 使用边界","",result.notice,"本工具不会自动联系商户、预订、付款、上传或发布内容。","");return lines.join("\n");}
  const api={ENGINE_VERSION,statusLabels,evaluate,report,clock,validity};if(typeof module==="object"&&module.exports)module.exports=api;else root.TravelCore=api;
})(globalThis);
